# Generated by Django 4.1.2 on 2023-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.AddField(
            model_name='myuser',
            name='genres',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
