# Generated by Django 4.1.2 on 2023-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_myuser_city_myuser_genres_myuser_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('strongly_agree', models.CharField(max_length=50)),
                ('agree', models.CharField(max_length=50)),
                ('neither', models.CharField(max_length=50)),
                ('disagree', models.CharField(max_length=50)),
                ('strongly_disagree', models.CharField(max_length=50)),
            ],
        ),
    ]
