# Generated by Django 4.1.2 on 2023-02-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_genres_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='keywords',
        ),
    ]
