# Generated by Django 4.1.2 on 2023-02-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_myuser_genres_remove_myuser_keywords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='questionText',
        ),
    ]
