# Generated by Django 4.1.2 on 2023-02-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='agree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='disagree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='neither',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='strongly_agree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='strongly_disagree',
            field=models.CharField(max_length=100),
        ),
    ]
