# Generated by Django 4.1.2 on 2023-02-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_question_agree_alter_question_disagree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionText',
            new_name='question_text',
        ),
    ]
