# Generated by Django 4.1.2 on 2023-02-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_questiontext_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
