# Generated by Django 4.1.2 on 2023-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=50),
        ),
    ]
