# Generated by Django 4.1.2 on 2023-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_game_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='userscore',
            field=models.CharField(max_length=50),
        ),
    ]
