# Generated by Django 4.1.2 on 2023-03-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_completedlist_dislikelist_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.TextField(),
        ),
    ]
