# Generated by Django 4.1.2 on 2023-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genre',
            field=models.TextField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='keyword',
            field=models.TextField(max_length=30000),
        ),
    ]
