# Generated by Django 4.1.2 on 2023-03-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_game_developer_alter_game_num_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrbs',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.CharField(max_length=200),
        ),
    ]
