# Generated by Django 4.1.2 on 2023-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_game_developer_alter_game_esrbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedlist',
            name='completed_list_game',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dislikelist',
            name='dislike_list_game',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb_rating',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrbs',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='userscore',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='play_list_game',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_players_preference',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='agree',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='disagree',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='neither',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='strongly_agree',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='strongly_disagree',
            field=models.TextField(max_length=500),
        ),
    ]
