# Generated by Django 4.1.2 on 2023-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_completedlist_completed_list_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='keywords',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
